### ISSUE TITLE
remove unittest2 requirement from < 2.7 setup when not not a test install

### ISSUE THREAD

**Issue by pdunnigan** [liris/websocket-client#156]
unittest2 is a requirement for this package when installing on python less than 2.7. setup.py has specific logic to handle this and the only file that references unittest or unittest2 is the testing script. 

unittest2 should not be a requirement for a non-test install and possibly may create problems if the latest unittest2 is installed on a python 2.6 machine. It seems that the new unittest2 1.0.0 (March 6th, 2015) is not installing well on RHEL 6.6 Python 2.6 which is causing websocket-client not to install.  

My suggestion is to only require the install unittest2 if the purpose of the install is to test websocket-client on < py2.7. An example of this in practice can be found here (which docker-py requires websocket-client on < py2.7):

https://github.com/docker/docker-py/blob/master/setup.py

thanks

**Comment by pdunnigan** [comment]
further digging: unittest2 now requires traceback2, which requires linecache2 which requires pbr. The install of the dependency linecache2 fails on python 2.6 with the following error:

ImportError: No module named pbr.core

I would suggest that websocket-client require unittest2==0.8.0 on < py2.7 to mitigate this problem.

**Comment by xZise** [comment]
Hi, I'd prefer if the solution in 7adeec3 was not so restrictive. pywikibot-core requires socketIO_client which requires websocket-client and that now requires unittest2 0.8.0. But why is unittest required for a normal install. Couldn't it be used as `tests_requires` in the `setup` call? Otherwise we need to lock to unittest2 0.8.0 too and I'd prefer if we don't have to install a specific version just because one dependency.
