### ISSUE TITLE
No terms and conditions in LICENSE file

### ISSUE THREAD

**Issue by eseraygun** [liris/websocket-client#282]
LPGL terms and conditions in LICENCE seem to have been removed in 7a9a6aff5a9baa2ef8942892aae23c3a1744b52b (v0.24.0). Was this intentional? If not, can you put them back so we can use the library in our projects safely?

**Comment by penrods** [comment]
Hey guys, I hope this isn't bad form but I wanted to check if the change on this that switched to LGPLv3 was fully intentional.  The move from LGPLv2.1 to LGPLv3 has some big implications and might significantly limit who uses this library.  This seems outside the scope of problem brought up by the original issue.

I can open another issue if you'd like to discuss there instead.
